package com.wts.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUnread<M extends BaseUnread<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * 工单序号
	 */
	public void setOrderGuid(java.lang.String orderGuid) {
		set("order_guid", orderGuid);
	}

	/**
	 * 工单序号
	 */
	public java.lang.String getOrderGuid() {
		return getStr("order_guid");
	}

	/**
	 * 标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	/**
	 * 标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 发送人
	 */
	public void setOrigSendPerson(java.lang.String origSendPerson) {
		set("origSendPerson", origSendPerson);
	}

	/**
	 * 发送人
	 */
	public java.lang.String getOrigSendPerson() {
		return getStr("origSendPerson");
	}

}
