package com.wts.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUnhandle<M extends BaseUnhandle<M>> extends Model<M> implements IBean {

	/**
	 * 序号
	 */
	public void setId(Integer id) {
		set("id", id);
	}
	
	/**
	 * 序号
	 */
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * 工单序号
	 */
	public void setOrderGuid(String orderGuid) {
		set("order_guid", orderGuid);
	}
	
	/**
	 * 工单序号
	 */
	public String getOrderGuid() {
		return getStr("order_guid");
	}

	/**
	 * 文档序号
	 */
	public void setFileGuid(String fileGuid) {
		set("file_guid", fileGuid);
	}
	
	/**
	 * 文档序号
	 */
	public String getFileGuid() {
		return getStr("file_guid");
	}

	/**
	 * 工单状态：已回复、已回退、待处理
	 */
	public void setOrderState(String orderState) {
		set("order_state", orderState);
	}
	
	/**
	 * 工单状态：已回复、已回退、待处理
	 */
	public String getOrderState() {
		return getStr("order_state");
	}

	/**
	 * 工单编号
	 */
	public void setOrderCode(String orderCode) {
		set("order_code", orderCode);
	}
	
	/**
	 * 工单编号
	 */
	public String getOrderCode() {
		return getStr("order_code");
	}

	/**
	 * 联系人
	 */
	public void setLinkPerson(String linkPerson) {
		set("link_person", linkPerson);
	}
	
	/**
	 * 联系人
	 */
	public String getLinkPerson() {
		return getStr("link_person");
	}

	/**
	 * 联系电话
	 */
	public void setLinkPhone(String linkPhone) {
		set("link_phone", linkPhone);
	}
	
	/**
	 * 联系电话
	 */
	public String getLinkPhone() {
		return getStr("link_phone");
	}

	/**
	 * 联系地址
	 */
	public void setLinkAddress(String linkAddress) {
		set("link_address", linkAddress);
	}
	
	/**
	 * 联系地址
	 */
	public String getLinkAddress() {
		return getStr("link_address");
	}

	/**
	 * 营商环境
	 */
	public void setBusinessEnvironment(String businessEnvironment) {
		set("business_environment", businessEnvironment);
	}
	
	/**
	 * 营商环境
	 */
	public String getBusinessEnvironment() {
		return getStr("business_environment");
	}

	/**
	 * 新版督察
	 */
	public void setNewSupervision(String newSupervision) {
		set("new_supervision", newSupervision);
	}
	
	/**
	 * 新版督察
	 */
	public String getNewSupervision() {
		return getStr("new_supervision");
	}

	/**
	 * 受理人员
	 */
	public void setAcceptPerson(String acceptPerson) {
		set("accept_person", acceptPerson);
	}
	
	/**
	 * 受理人员
	 */
	public String getAcceptPerson() {
		return getStr("accept_person");
	}

	/**
	 * 受理员编号
	 */
	public void setAcceptPersonCode(String acceptPersonCode) {
		set("accept_person_code", acceptPersonCode);
	}
	
	/**
	 * 受理员编号
	 */
	public String getAcceptPersonCode() {
		return getStr("accept_person_code");
	}

	/**
	 * 受理渠道
	 */
	public void setAcceptChannel(String acceptChannel) {
		set("accept_channel", acceptChannel);
	}
	
	/**
	 * 受理渠道
	 */
	public String getAcceptChannel() {
		return getStr("accept_channel");
	}

	/**
	 * 办理类型
	 */
	public void setHandleType(String handleType) {
		set("handle_type", handleType);
	}
	
	/**
	 * 办理类型
	 */
	public String getHandleType() {
		return getStr("handle_type");
	}

	/**
	 * 来电类别
	 */
	public void setPhoneType(String phoneType) {
		set("phone_type", phoneType);
	}
	
	/**
	 * 来电类别
	 */
	public String getPhoneType() {
		return getStr("phone_type");
	}

	/**
	 * 录入时间
	 */
	public void setWriteTime(String writeTime) {
		set("write_time", writeTime);
	}
	
	/**
	 * 录入时间
	 */
	public String getWriteTime() {
		return getStr("write_time");
	}

	/**
	 * 紧急程度
	 */
	public void setUrgencyDegree(String urgencyDegree) {
		set("urgency_degree", urgencyDegree);
	}
	
	/**
	 * 紧急程度
	 */
	public String getUrgencyDegree() {
		return getStr("urgency_degree");
	}

	/**
	 * 问题分类
	 */
	public void setProblemClassification(String problemClassification) {
		set("problem_classification", problemClassification);
	}
	
	/**
	 * 问题分类
	 */
	public String getProblemClassification() {
		return getStr("problem_classification");
	}

	/**
	 * 是否保密
	 */
	public void setIsSecret(String isSecret) {
		set("is_secret", isSecret);
	}
	
	/**
	 * 是否保密
	 */
	public String getIsSecret() {
		return getStr("is_secret");
	}

	/**
	 * 是否回复
	 */
	public void setIsReply(String isReply) {
		set("is_reply", isReply);
	}
	
	/**
	 * 是否回复
	 */
	public String getIsReply() {
		return getStr("is_reply");
	}

	/**
	 * 回复备注
	 */
	public void setReplyRemark(String replyRemark) {
		set("reply_remark", replyRemark);
	}
	
	/**
	 * 回复备注
	 */
	public String getReplyRemark() {
		return getStr("reply_remark");
	}

	/**
	 * 问题描述
	 */
	public void setProblemDescription(String problemDescription) {
		set("problem_description", problemDescription);
	}
	
	/**
	 * 问题描述
	 */
	public String getProblemDescription() {
		return getStr("problem_description");
	}

	/**
	 * 附件
	 */
	public void setEnclosure(String enclosure) {
		set("enclosure", enclosure);
	}
	
	/**
	 * 附件
	 */
	public String getEnclosure() {
		return getStr("enclosure");
	}

	/**
	 * 发送人
	 */
	public void setSendPerson(String sendPerson) {
		set("send_person", sendPerson);
	}
	
	/**
	 * 发送人
	 */
	public String getSendPerson() {
		return getStr("send_person");
	}

	/**
	 * 发送时间
	 */
	public void setSendTime(String sendTime) {
		set("send_time", sendTime);
	}
	
	/**
	 * 发送时间
	 */
	public String getSendTime() {
		return getStr("send_time");
	}

	/**
	 * 办理时限
	 */
	public void setEndDate(String endDate) {
		set("end_date", endDate);
	}
	
	/**
	 * 办理时限
	 */
	public String getEndDate() {
		return getStr("end_date");
	}

	/**
	 * 转办意见
	 */
	public void setTransferOpinion(String transferOpinion) {
		set("transfer_opinion", transferOpinion);
	}
	
	/**
	 * 转办意见
	 */
	public String getTransferOpinion() {
		return getStr("transfer_opinion");
	}

	/**
	 * 转办流程
	 */
	public void setTransferProcess(String transferProcess) {
		set("transfer_process", transferProcess);
	}
	
	/**
	 * 转办流程
	 */
	public String getTransferProcess() {
		return getStr("transfer_process");
	}

	/**
	 * 备注
	 */
	public void setRemark(String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public String getRemark() {
		return getStr("remark");
	}

	/**
	 * 下载时间
	 */
	public void setDownTime(java.util.Date downTime) {
		set("down_time", downTime);
	}
	
	/**
	 * 下载时间
	 */
	public java.util.Date getDownTime() {
		return get("down_time");
	}

}
