package com.wts.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseExpire<M extends BaseExpire<M>> extends Model<M> implements IBean {

	/**
	 * 序号
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 序号
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 工单序号
	 */
	public void setOrderGuid(java.lang.String orderGuid) {
		set("order_guid", orderGuid);
	}
	
	/**
	 * 工单序号
	 */
	public java.lang.String getOrderGuid() {
		return getStr("order_guid");
	}

	/**
	 * 工单编号
	 */
	public void setOrderCode(java.lang.String orderCode) {
		set("order_code", orderCode);
	}
	
	/**
	 * 工单编号
	 */
	public java.lang.String getOrderCode() {
		return getStr("order_code");
	}

	/**
	 * 办理时限
	 */
	public void setEndDate(java.lang.String endDate) {
		set("end_date", endDate);
	}
	
	/**
	 * 办理时限
	 */
	public java.lang.String getEndDate() {
		return getStr("end_date");
	}

}
