package com.wts.entity.model;

import com.wts.entity.model.base.BaseWorkorder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Workorder extends BaseWorkorder<Workorder> {
	
}
